services:
  backend:
    build: .
    depends_on:
      - database
    ports:
      - "4000:4000"
    networks:
      - skillstackr

  database:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - skillstackr
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: skillstackr_dev

networks:
  skillstackr:
