name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #
  #     - name: Setup SSH
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa
  #         ssh-keyscan -H ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts
  #     
  #     - name: Deploy to EC2
  #       run: |
  #         rsync -avz --delete . ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}:~/app
  #
  #     - name: Install dependencies
  #       run: |
  #         ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} ". ~/.asdf/asdf.sh && cd ~/app && make setup"
